cd ~/Desktop/mega/b12
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/admin-console
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/admin-tools
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/assets-service
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/auth-service
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/b12-clitools
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/config-service
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/data-service
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/game-installation
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/game-monitoring-service
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/generateDashboard
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/push-notifications-service
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/push-notifications-tool
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/rb-service
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/services-common
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/sysadmin
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-gameenv
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-global
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-instance-module
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-task-state-notifications
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/tests
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/translation-service
git clone  https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/user-data
