#!/bin/bash
# set -x

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

groupadd -f sftp

sed -i "s/^Subsystem sftp \/usr\/lib\/openssh\/sftp\-server/# Subsystem sftp \/usr\/lib\/openssh\/sftp-server/g" /etc/ssh/sshd_config

if ! grep -q 'Subsystem sftp internal-sftp' /etc/ssh/sshd_config; then
  cat >> /etc/ssh/sshd_config << EOF

Subsystem sftp internal-sftp

Match group sftp
  ChrootDirectory %h
  X11Forwarding no
  AllowTcpForwarding no
  ForceCommand internal-sftp
EOF

  echo "Chrooted SFTP configured."
else
  echo "Chrooted SFTP already configured."
fi

service ssh restart

exit 0
